### ISSUE TITLE
bounding boxes coordinates

### ISSUE THREAD

**Issue by anantnd** [doc-analysis/TableBank#17]
how do I get the coordinates of the boxes?

**Comment by anantnd** [comment]
what is the output of cls_boxes? how do I get coordinates of the boxes in (x1,y1,x2,y2) order

**Comment by liminghao1630** [comment]
Please describe your problem in detail.   Is your question about detectron?

**Comment by anantnd** [comment]
yes, it was about detectron. I figured it out though.

**Comment by iambatman07** [comment]
Hey, how did you figure that out ? Could you tell that .@anantnd

> yes, it was about detectron. I figured it out though.

**Comment by anantnd** [comment]
@iambatman07 all the coordinates are stored in cls_boxes

**Comment by iambatman07** [comment]
> @iambatman07 all the coordinates are stored in cls_boxes

Could you please tell me if it's in points or pixels or inch wise. That information is not available though, also if it's measured top down or bottom up. Thanks @anantnd

**Comment by anantnd** [comment]
pixels. (x1, y1, x2, y2) -> where, (x1, y1) = top left & (x2, y2) = bottom right

**Comment by iambatman07** [comment]
Thanks man @anantnd
