### ISSUE TITLE
Document about how to use the trained model

### ISSUE THREAD

**Issue by perfectspr** [doc-analysis/TableBank#2]

**Comment by liminghao1630** [comment]
Detectron format trained model: 
https://github.com/facebookresearch/Detectron/blob/master/GETTING_STARTED.md #Inference with Pretrained Models
OpenNMT format trained model: 
http://opennmt.net/OpenNMT-py/im2text.html  #Translate the images.

**Comment by perfectspr** [comment]
Thank you.
