### ISSUE TITLE
do you plan to release the code for generating ground truth from .docx/.doc and Latex files 

### ISSUE THREAD

**Issue by kegeyang** [doc-analysis/TableBank#3]

**Comment by haoransh** [comment]
Same question. It would be super helpful if we could have the ground-truth of the bounding box of each cell in tables, by modifying your data processing code. Maybe in a similar way to your detection for table boundary? (add bounding box to the cell and check the pixel difference of the compiled document image)

**Comment by liminghao1630** [comment]
Sorry, but we are not planning to release code for the time being.
