### ISSUE TITLE
Reproduce Precision, Recall and F1 score results from Detectron2 checkpoints 

### ISSUE THREAD

**Issue by francescoperessini** [doc-analysis/TableBank#30]
Is it possible to have the code used for calculate the Precision, Recall and F1 score reported in the table here on GitHub? I'm talking about the results obtained with the last released checkpoints obtained with Detectron2. 

The instruction on the paper are not so clear...

**Comment by divypandya** [comment]
@francescoperessini  Hey did you find any solution for calculating the F1 scores for detectron2?
