### ISSUE TITLE
how to extract the dataset ? 

### ISSUE THREAD

**Issue by GTimothee** [doc-analysis/TableBank#34]
I downloaded the dataset parts but I cannot manage to extract the files correctly. 

I tried different commands cited here: https://unix.stackexchange.com/questions/40480/how-to-unzip-a-multipart-spanned-zip-on-linux 

But the only successful method was this one : 

```
cat test.zip.* >test.zip
zip -FF test.zip --out test-full.zip
unzip test-full.zip
```

However, after the extraction one of the annotation json file is broken and has not been extracted correctly.

Can someone share their way to extract the dataset please ?

**Comment by GTimothee** [comment]
Some files were not fully downloaded. By the way it could be useful to use hashing for each file to ensure that the files are not corrupted.

**Comment by MaveriQ** [comment]
Hi. I am getting the same errors, despite downloading the dataset multiple times. Were you able to fix the errors with zip files?
Thanks
