### ISSUE TITLE
Can you release the names of the files in test set to reproduce the result reported in your paper?

### ISSUE THREAD

**Issue by haoransh** [doc-analysis/TableBank#5]
As topic. This can help to reproduce your experiments.

**Comment by haoransh** [comment]
By the way, I give a simple tutorial on how to use your pretrained model to perform table detection here https://github.com/haoransh/TableBank/blob/master/TestPretrainedModel.md. The detection on the sampled TableBank data looks perfect! Thanks for your great work!! Would you like to merge the repo maybe?

**Comment by liminghao1630** [comment]
I read the document you wrote and it is pretty good.   I'm not sure how to merge your repo, maybe you should start a new pull request?

**Comment by haoransh** [comment]
Yeah, Thanks! I have created a pull request.

**Comment by doc-analysis** [comment]
Merged.

**Comment by rockyzhengwu** [comment]
```

python tools/infer_simple.py --cfg $MODEL_PATH --output-dir /tmp/detectron-tablebank --image-ext jpg \
    --wts $CONFIG_MODEL /home/shr/TableBank/data/Sampled_Detection_data/Latex/images
```
I think this line should 
```
python tools/infer_simple.py --cfg $CONFIG_MODEL --output-dir /tmp/detectron-tablebank --image-ext jpg \
    --wts $MODEL_PATH  /home/shr/TableBank/data/Sampled_Detection_data/Latex/images
```

**Comment by haoransh** [comment]
Thanks! You are right. To be clear, `--cfg` should be the YAML file of the model architecture, and `--wts` should be the pickled file `.pkl` of the model parameters.

**Comment by doc-analysis** [comment]
I have I have fixed this error.
