### ISSUE TITLE
some table not labeled 

### ISSUE THREAD

**Issue by rockyzhengwu** [doc-analysis/TableBank#9]
I found there is some problem in the data ,  table not labeled . two example from Word.json
```
{'category_id': 1, 'area': 46280, 'iscrowd': 0, 'segmentation': [[71, 176, 71, 280, 516, 280, 516, 176]], 'id': 69303, 'image_id': 53565, 'bbox': [71, 176, 445, 104]}
```
```
{'category_id': 1, 'area': 143613, 'iscrowd': 0, 'segmentation': [[66, 72, 66, 269, 795, 269, 795, 72]], 'id': 67935, 'image_id': 52492, 'bbox': [66, 72, 729, 197]}
```

![53565](https://user-images.githubusercontent.com/10402091/60758300-6a1ebe80-a048-11e9-8a4b-4082408cde90.png)

![52492](https://user-images.githubusercontent.com/10402091/60758281-317ee500-a048-11e9-8cea-50db2649ee05.png)

**Comment by lumiaomiao** [comment]
Hi, how did you download the dataset? I have received the download link from author, but cannot download the dataset by "wget" and "browser". Could you introduce you means?

**Comment by rockyzhengwu** [comment]
@lumiaomiao sorry, I can't remember about that

**Comment by doc-analysis** [comment]
@rockyzhengwu The method we used can not guarantee that all tables are marked. Table will be detected and labeled automatically by code, which means some error may cause a little table unlabeled. 

> We randomly sample 1,000 examples from the dataset and manually check the bounding boxes of tables. We observe that only 5 of them are incorrectly labeled, which demonstrates the high quality of this dataset.

For detail, see [our paper](https://arxiv.org/abs/1903.01949).

**Comment by rockyzhengwu** [comment]
Thanks
